### ISSUE TITLE
Icmp-Redirect EthARP class does not take SrcMac argument

### ISSUE THREAD

**Issue by dtrizna** [lgandx/Responder#103]
```
# python tools/Icmp-Redirect.py -i <MYIP> -g <GW> -t <TARGET_SAME_BROADCAST_NET> -r <DIFFERENT_NET_IP1> -s <DIFFERENT_NET_IP2> -I eth1

ICMP Redirect Utility 0.1.
Created by Laurent Gaffie, please send bugs/comments to laurent.gaffie@gmail.com

This utility combined with Responder is useful when you're sitting on a Windows based network.
Most Linux distributions discard by default ICMP Redirects.

Hit CTRL-C to kill this script
[+]Automatic mode enabled
An iptable rules has been added for both DNS servers.
Traceback (most recent call last):
  File "tools/Icmp-Redirect.py", line 238, in <module>
    FindWhatToDo(ToThisHost2)
  File "tools/Icmp-Redirect.py", line 219, in FindWhatToDo
    RunThisInLoop(ToThisHost, ToThisHost2,OURIP)
  File "tools/Icmp-Redirect.py", line 233, in RunThisInLoop
    IcmpRedirectSock(DestinationIP=dns1)
  File "tools/Icmp-Redirect.py", line 198, in IcmpRedirectSock
    PrintMac,DestMac = ReceiveArpFrame(VictimIP)
  File "tools/Icmp-Redirect.py", line 182, in ReceiveArpFrame
    Eth = EthARP(SrcMac=OurMac)
TypeError: __init__() got an unexpected keyword argument 'SrcMac'
```

**Comment by dtrizna** [comment]
When printing s.getsockname() it outputs:
```
('eth1', 2054, 0, 1, "\x08\x00'J\xa9\xd2")
```

Tried to tune EthARP class by myself, but this OrderedDict approach of handling kwargs is new to me, sorry, wasn't able to fix..

**Comment by dtrizna** [comment]
Figured out, this was problem with `packets` dependency `Packet` class.
I've installed it via pip, because script didn't seen this dependency (as modules are located in repo root, while script in tools folder).

Dumb module copy into tools directory solved the problem.
