### ISSUE TITLE
Responder Traceback error

### ISSUE THREAD

**Issue by tsrofj** [lgandx/Responder#116]
Getting tracebacks when trying to run Responder. Fresh install of Python3.7 and fresh download/install of Responder.

Error condition with various Responder options.

```user@user:14:10:16 CST - ~/Downloads/Responder-master $ cat /etc/os-release 
NAME="Linux Mint"
VERSION="18.3 (Sylvia)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 18.3"
VERSION_ID="18.3"
HOME_URL="http://www.linuxmint.com/"
SUPPORT_URL="http://forums.linuxmint.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/linuxmint/"
VERSION_CODENAME=sylvia
UBUNTU_CODENAME=xenial
user@user:14:10:22 CST - ~/Downloads/Responder-master $ sudo python3.7 Responder.py -I enp0s31f6 -rPv
                                         __
  .----.-----.-----.-----.-----.-----.--|  |.-----.----.
  |   _|  -__|__ --|  _  |  _  |     |  _  ||  -__|   _|
  |__| |_____|_____|   __|_____|__|__|_____||_____|__|
                   |__|

           NBT-NS, LLMNR & MDNS Responder 3.0.0.0

  Author: Laurent Gaffie (laurent.gaffie@gmail.com)
  To kill this script hit CTRL-C

Traceback (most recent call last):
  File "Responder.py", line 58, in <module>
    settings.Config.populate(options)
  File "/home/user/Downloads/Responder-master/settings.py", line 190, in populate
    self.Bind_To         = utils.FindLocalIP(self.Interface, self.OURIP)
  File "/home/user/Downloads/Responder-master/utils.py", line 138, in FindLocalIP
    s.setsockopt(socket.SOL_SOCKET, 25, Iface+'\0')
TypeError: a bytes-like object is required, not 'str'
user@user:14:10:26 CST - ~/Downloads/Responder-master $ 

user@user:14:10:26 CST - ~/Downloads/Responder-master $ sudo python3.7 Responder.py -I enp0s31f6 -wfv
                                         __
  .----.-----.-----.-----.-----.-----.--|  |.-----.----.
  |   _|  -__|__ --|  _  |  _  |     |  _  ||  -__|   _|
  |__| |_____|_____|   __|_____|__|__|_____||_____|__|
                   |__|

           NBT-NS, LLMNR & MDNS Responder 3.0.0.0

  Author: Laurent Gaffie (laurent.gaffie@gmail.com)
  To kill this script hit CTRL-C

Traceback (most recent call last):
  File "Responder.py", line 58, in <module>
    settings.Config.populate(options)
  File "/home/jforst/Downloads/Responder-master/settings.py", line 190, in populate
    self.Bind_To         = utils.FindLocalIP(self.Interface, self.OURIP)
  File "/home/jforst/Downloads/Responder-master/utils.py", line 138, in FindLocalIP
    s.setsockopt(socket.SOL_SOCKET, 25, Iface+'\0')
TypeError: a bytes-like object is required, not 'str'```

**Comment by lgandx** [comment]
Thanks for your report, this issue has been fixed.
