### ISSUE TITLE
"Error: Interface not found" when running in WSL

### ISSUE THREAD

**Issue by jankais3r** [lgandx/Responder#118]
I am running Responder in Ubuntu WSL, Python 3:
```
root@XXX:~/Responder# ifconfig
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 1500
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0xfe<compat,link,site,host>
        loop  (Local Loopback)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wifi0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.31.115.119  netmask 255.255.255.128  broadcast 172.31.115.127
        inet6 fe80::9d30:cc72:e9f8:5a7e  prefixlen 64  scopeid 0xfd<compat,link,site,host>
        ether 18:ff:0e:21:68:c3  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

root@XXX:~/Responder# ./Responder.py -wFI wifi0
                                         __
  .----.-----.-----.-----.-----.-----.--|  |.-----.----.
  |   _|  -__|__ --|  _  |  _  |     |  _  ||  -__|   _|
  |__| |_____|_____|   __|_____|__|__|_____||_____|__|
                   |__|

           NBT-NS, LLMNR & MDNS Responder 3.0.0.0

  Author: Laurent Gaffie (laurent.gaffie@gmail.com)
  To kill this script hit CTRL-C

[!] Error: wifi0: Interface not found
root@XXX:~/Responder# ./Responder.py -wFI lo
                                         __
  .----.-----.-----.-----.-----.-----.--|  |.-----.----.
  |   _|  -__|__ --|  _  |  _  |     |  _  ||  -__|   _|
  |__| |_____|_____|   __|_____|__|__|_____||_____|__|
                   |__|

           NBT-NS, LLMNR & MDNS Responder 3.0.0.0

  Author: Laurent Gaffie (laurent.gaffie@gmail.com)
  To kill this script hit CTRL-C

[!] Error: lo: Interface not found
```

**Comment by lgandx** [comment]
I can't reproduce with the latest version :/

**Comment by jankais3r** [comment]
There is a [duplicate issue](https://github.com/SpiderLabs/Responder/issues/155) about this in the original repository.

When I went to that issue now in order to copy the link, I noticed that yesterday somebody commented that using -I and -i together gets around this 'interface not found' error. Indeed it does, but it fails on something else.

```root@XXX:~/Responder# ./Responder.py -wFI wifi0 -i 10.31.115.119
                                         __
  .----.-----.-----.-----.-----.-----.--|  |.-----.----.
  |   _|  -__|__ --|  _  |  _  |     |  _  ||  -__|   _|
  |__| |_____|_____|   __|_____|__|__|_____||_____|__|
                   |__|

           NBT-NS, LLMNR & MDNS Responder 3.0.0.0

  Author: Laurent Gaffie (laurent.gaffie@gmail.com)
  To kill this script hit CTRL-C


[+] Poisoners:
    LLMNR                      [ON]
    NBT-NS                     [ON]
    DNS/MDNS                   [ON]

[+] Servers:
    HTTP server                [ON]
    HTTPS server               [ON]
    WPAD proxy                 [ON]
    Auth proxy                 [OFF]
    SMB server                 [ON]
    Kerberos server            [ON]
    SQL server                 [ON]
    FTP server                 [ON]
    IMAP server                [ON]
    POP3 server                [ON]
    SMTP server                [ON]
    DNS server                 [ON]
    LDAP server                [ON]
    RDP server                 [ON]

[+] HTTP Options:
    Always serving EXE         [OFF]
    Serving EXE                [OFF]
    Serving HTML               [OFF]
    Upstream Proxy             [OFF]

[+] Poisoning Options:
    Analyze Mode               [OFF]
    Force WPAD auth            [ON]
    Force Basic Auth           [OFF]
    Force LM downgrade         [OFF]
    Fingerprint hosts          [OFF]

[+] Generic Options:
    Responder NIC              [wifi0]
    Responder IP               [10.31.115.119]
    Challenge set              [random]
    Don't Respond To Names     ['ISATAP']



[!] Error starting UDP server on port 138, check permissions or other servers running.
[!] Error starting UDP server on port 137, check permissions or other servers running.
[!] Error starting TCP server on port 80, check permissions or other servers running.
[!] Error starting UDP server on port 5353, check permissions or other servers running.
[!] Error starting SSL server on port 443, check permissions or other servers running.
[!] Error starting TCP server on port 3141, check permissions or other servers running.
[!] Error starting TCP server on port 3389, check permissions or other servers running.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./Responder.py", line 189, in serve_LLMNR_poisoner
    server = ThreadingUDPLLMNRServer((host, port), handler)
  File "/usr/lib/python3.6/socketserver.py", line 456, in __init__
    self.server_bind()
  File "./Responder.py", line 156, in server_bind
    self.socket.setsockopt(socket.SOL_SOCKET, 25, bytes(settings.Config.Interface+'\0', 'utf-8'))
OSError: [Errno 92] Protocol not available
[!] Error starting UDP server on port 88, check permissions or other servers running.

[!] Error starting TCP server on port 1433, check permissions or other servers running.
[!] Error starting TCP server on port 445, check permissions or other servers running.
[!] Error starting TCP server on port 110, check permissions or other servers running.
[!] Error starting TCP server on port 21, check permissions or other servers running.
[!] Error starting TCP server on port 25, check permissions or other servers running.
[!] Error starting TCP server on port 143, check permissions or other servers running.
[+] Listening for events...
[!] Error starting UDP server on port 1434, check permissions or other servers running.
[!] Error starting TCP server on port 88, check permissions or other servers running.
[!] Error starting TCP server on port 587, check permissions or other servers running.
[!] Error starting TCP server on port 53, check permissions or other servers running.
[!] Error starting TCP server on port 389, check permissions or other servers running.
[!] Error starting TCP server on port 139, check permissions or other servers running.
[!] Error starting UDP server on port 53, check permissions or other servers running.```

**Comment by jrobber1** [comment]
This issue persists 
[!] Error starting UDP server on port 88, check permissions or other servers running.

[!] Error starting TCP server on port 1433, check permissions or other servers running.
[!] Error starting TCP server on port 445, check permissions or other servers running.
[!] Error starting TCP server on port 110, check permissions or other servers running.
[!] Error starting TCP server on port 21, check permissions or other servers running.
[!] Error starting TCP server on port 25, check permissions or other servers running.
[!] Error starting TCP server on port 143, check permissions or other servers running.
[+] Listening for events...
[!] Error starting UDP server on port 1434, check permissions or other servers running.
[!] Error starting TCP server on port 88, check permissions or other servers running.
[!] Error starting TCP server on port 587, check permissions or other servers running.
[!] Error starting TCP server on port 53, check permissions or other servers running.
[!] Error starting TCP server on port 389, check permissions or other servers running.
[!] Error starting TCP server on port 139, check permissions or other servers running.
[!] Error starting UDP server on port 53, check permissions or other servers running.

**Comment by Lyonid** [comment]
I know this is 2 years old, but I'm still having the same issue when specifying both -i and -I
Anyone actually solved this^

**Comment by TheLime1** [comment]
nope
