### ISSUE TITLE
MultiRelay python3 UserDict

### ISSUE THREAD

**Issue by HiddeSmit** [lgandx/Responder#119]
Running MultiRelay gives the following error:
```
Traceback (most recent call last):
  File "/usr/share/responder/tools/MultiRelay.py", line 39, in <module>
    from MultiRelay.RelayMultiCore import *
  File "/usr/share/responder/tools/MultiRelay/RelayMultiCore.py", line 32, in <module>
    from SMBFinger.Finger import ShowSmallResults
  File "/usr/share/responder/tools/SMBFinger/Finger.py", line 21, in <module>
    from .odict import OrderedDict
  File "/usr/share/responder/tools/SMBFinger/odict.py", line 1, in <module>
    from UserDict import DictMixin
ModuleNotFoundError: No module named 'UserDict'
```

Apparently Python3 no longer supports UserDict module. It has been moved to the collections module.

**Comment by danielfal** [comment]
Same issue here, running MultiRelay from /tools/ gives this output:
![image](https://user-images.githubusercontent.com/38814831/77949338-c55aa600-7294-11ea-9830-1b012dd48f21.png)

**Comment by meow-tech** [comment]
I have the same issue:
`Traceback (most recent call last):
  File "./MultiRelay.py", line 39, in <module>
    from MultiRelay.RelayMultiCore import *
  File "/usr/share/responder/tools/MultiRelay/RelayMultiCore.py", line 32, in <module>
    from SMBFinger.Finger import ShowSmallResults
  File "/usr/share/responder/tools/SMBFinger/Finger.py", line 21, in <module>
    from .odict import OrderedDict
  File "/usr/share/responder/tools/SMBFinger/odict.py", line 1, in <module>
    from UserDict import DictMixin
ModuleNotFoundError: No module named 'UserDict'
`
When using Python 2.7 it works. However once I get a shell unable to issue any commands and get this error:
`Connected to 172.16.23.101 as LocalSystem.
C:\Windows\system32\:#whoami
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./MultiRelay.py", line 164, in get_command
    Cmd = [input("C:\\Windows\\system32\\:#")]
  File "<string>", line 1, in <module>
NameError: name 'whoami' is not defined
`

**Comment by skimpniff** [comment]
I am getting the same issue with python3. With python2/2.7 i get 
![image](https://user-images.githubusercontent.com/64666615/80846060-fabe2080-8bbf-11ea-9568-5170568afb0c.png)
Kali, fully updated as of today.

**Comment by lgandx** [comment]
Thanks for submitting this issue. Multirelay has not yet been ported to python3, it's the only tool left to do. I'm pretty busy these days... when i'll have a minute i'll port it to py3!
Thanks for your patience and reports.

**Comment by Rourke101** [comment]
Mmm.. Why am I getting this?

I try to check if I was using the wrong Python, but the script forces python3.

```
kali@kali:~$ responder-MultiRelay 
/usr/share/responder/tools/MultiRelay.py:418: SyntaxWarning: "is not" with a literal. Did you mean "!="?                                                        
  if data.find("NTLM") is not -1:                                                                                                                               
/usr/share/responder/tools/MultiRelay.py:423: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if data.find("NTLM") is not -1:
Traceback (most recent call last):
  File "/usr/share/responder/tools/MultiRelay.py", line 39, in <module>
    from MultiRelay.RelayMultiCore import *
  File "/usr/share/responder/tools/MultiRelay/RelayMultiCore.py", line 32, in <module>
    from SMBFinger.Finger import ShowSmallResults
  File "/usr/share/responder/tools/SMBFinger/Finger.py", line 21, in <module>
    from .odict import OrderedDict
  File "/usr/share/responder/tools/SMBFinger/odict.py", line 1, in <module>
    from UserDict import DictMixin
ModuleNotFoundError: No module named 'UserDict'
kali@kali:~$ sudo apt install responder 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
responder is already the newest version (3.0.1.0-0kali1).
```

**Comment by HBT89** [comment]
Issue closed but still exists.
Is there an expected fix?

**Comment by lgandx** [comment]
This issue has been fixed when MultiRelay was ported to py3.
