### ISSUE TITLE
MultiRelay_SintaxERROR...

### ISSUE THREAD

**Issue by BuSh1DO** [lgandx/Responder#147]
after workaround for cryptohash and pycryptodome, the tool stay with problems:

root@somehost:/opt/Responder/tools# python3 MultiRelay.py
  File "/opt/Responder/tools/MultiRelay.py", line 30
    print "\033[1;31m\nCrypto lib is not installed. You won't be able to live dump the hashes."
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("\033[1)?
root@somehost:/opt/Responder/tools#

when we fix the print syntax problem, we get other syntax problems

root@somehost:/opt/Responder/tools# python3 MultiRelay_TM.py
  File "/opt/Responder/tools/MultiRelay_TM.py", line 222
    if NTLM_Auth:
TabError: inconsistent use of tabs and spaces in indentation
root@somehost:/opt/Responder/tools#

**Comment by BuSh1DO** [comment]
the problem is indentation...
i corrected one file (Multirelay.py) but it gave me more errors:

Traceback (most recent call last):
  File "/opt/Responder/tools/mr.py", line 38, in <module>
    from MultiRelay.RelayMultiPackets import *
  File "/opt/Responder/tools/MultiRelay/RelayMultiPackets.py", line 393
    self.fields["ApplicationHeaderTagLenOfLen"] = "\x82"
TabError: inconsistent use of tabs and spaces in indentation

and some pip packages where the name differs from the python2.7 to python3 (SocketServer =>socketserver)

**Comment by Moron-bit** [comment]
from what ive understood MultiRelay.py is not fully python3 supported...

these steps will make multirealy.py working on kali linux:

1. sudo apt-get install python-dev
2. git clone https://github.com/pycrypto/pycrypto
3. cd pycrypto
4. sudo python ./setup.py build
5. sudo python ./setup.py install

like @bagels-sec suggested here : 
https://github.com/lgandx/Responder/issues/144#issuecomment-770043658

good luck :)
