### ISSUE TITLE
[AttributeError] Multiple errors running tools/ scripts

### ISSUE THREAD

**Issue by s7x** [lgandx/Responder#154]
Hello @lgandx!

I'm encountering multiple errors when trying to run the following tools in the tools/ directory (cmd + stack trace attached to each tool):

- DHCP.py

> python3 DHCP.py -h

```
Traceback (most recent call last):
  File "/tmp/Responder/tools/DHCP.py", line 26, in <module>
    from packets import Packet
  File "/tmp/Responder/packets.py", line 972, in <module>
    class SMBNegoAnsLM(Packet):
  File "/tmp/Responder/packets.py", line 983, in SMBNegoAnsLM
    ("Systemtime",   SMBTime()),
  File "/tmp/Responder/utils.py", line 58, in SMBTime
    if settings.Config.PY2OR3 == "PY3":
AttributeError: module 'settings' has no attribute 'Config'
```

- FindSMB2UPTime.py

> python FindSMB2UPTime.py -h

```
Traceback (most recent call last):
  File "/tmp/Responder/tools/FindSMB2UPTime.py", line 24, in <module>
    from packets import SMBHeaderReq, SMB2NegoReq, SMB2NegoDataReq
  File "/tmp/Responder/packets.py", line 972, in <module>
    class SMBNegoAnsLM(Packet):
  File "/tmp/Responder/packets.py", line 983, in SMBNegoAnsLM
    ("Systemtime",   SMBTime()),
  File "/tmp/Responder/utils.py", line 58, in SMBTime
    if settings.Config.PY2OR3 == "PY3":
AttributeError: module 'settings' has no attribute 'Config'
```

- FindSQLSrv.py

> python FindSQLSrv.py -h

```
MSSQL Server Finder 0.2
Traceback (most recent call last):
  File "/tmp/Responder/tools/FindSQLSrv.py", line 24, in <module>
    s.sendto('\x02',('255.255.255.255',1434))
TypeError: a bytes-like object is required, not 'str'
```

- Icmp-Redirect.py

> python Icmp-Redirect.py -h

```
Traceback (most recent call last):
  File "/tmp/Responder/tools/Icmp-Redirect.py", line 28, in <module>
    from packets import Packet
  File "../packets.py", line 972, in <module>
    class SMBNegoAnsLM(Packet):
  File "../packets.py", line 983, in SMBNegoAnsLM
    ("Systemtime",   SMBTime()),
  File "../utils.py", line 58, in SMBTime
    if settings.Config.PY2OR3 == "PY3":
AttributeError: module 'settings' has no attribute 'Config'
```

**Kernel**: Linux 5.11.9-hardened1-1-hardened
**OS**: ArchLinux
**Responder Version**: Responder 3.0.3.0 (git clone'd today)
**Python Version**: Python 3.9.2

Hope I gave you enough information. Ping me if you need more.
Thanks for your work on Responder & all the rest.

**Comment by lgandx** [comment]
Hi, 

Thanks for you bug report, a few tools were not updated to py3. It's a great opportunity to do it now.
Check for an update soon.

Thanks!

**Comment by s7x** [comment]
Hi,

Thank you for your work! It'll be updated and available in the BlackArch Linux repos.

Regards
