### ISSUE TITLE
Traceback from the -d NBT-NS flag while connected to a VPN

### ISSUE THREAD

**Issue by wallywhatever** [lgandx/Responder#176]
This option works correctly while using eth0. VPN connection is an OpenVPN profile generated by tryhackme.com for one of their networks. It was imported locally via nmcli. I'm running a fully updated kali vm and I have manually cloned the most recent responder version. Thanks!

```
└─$ sudo responder -I tun0 -d                                                                                     
                                         __
  .----.-----.-----.-----.-----.-----.--|  |.-----.----.
  |   _|  -__|__ --|  _  |  _  |     |  _  ||  -__|   _|
  |__| |_____|_____|   __|_____|__|__|_____||_____|__|
                   |__|

           NBT-NS, LLMNR & MDNS Responder 3.0.8.0

  Author: Laurent Gaffie (laurent.gaffie@gmail.com)
  To kill this script hit CTRL-C


[+] Poisoners:
    LLMNR                      [ON]
    NBT-NS                     [ON]
    DNS/MDNS                   [ON]
    DHCP                       [ON]

[+] Servers:
    HTTP server                [ON]
    HTTPS server               [ON]
    WPAD proxy                 [OFF]
    Auth proxy                 [OFF]
    SMB server                 [ON]
    Kerberos server            [ON]
    SQL server                 [ON]
    FTP server                 [ON]
    IMAP server                [ON]
    POP3 server                [ON]
    SMTP server                [ON]
    DNS server                 [ON]
    LDAP server                [ON]
    RDP server                 [ON]
    DCE-RPC server             [ON]
    WinRM server               [ON]

[+] HTTP Options:
    Always serving EXE         [OFF]
    Serving EXE                [OFF]
    Serving HTML               [OFF]
    Upstream Proxy             [OFF]

[+] Poisoning Options:
    Analyze Mode               [OFF]
    Force WPAD auth            [OFF]
    Force Basic Auth           [OFF]
    Force LM downgrade         [OFF]
    Force ESS downgrade        [OFF]
    Fingerprint hosts          [OFF]

[+] Generic Options:
    Responder NIC              [tun0]
    Responder IP               [10.50.59.17]
    Challenge set              [random]
    Don't Respond To Names     ['ISATAP']

[+] Current Session Variables:
    Responder Machine Name     [WIN-6H91XONAJZ3]
    Responder Domain Name      [K869.LOCAL]
    Responder DCE-RPC Port     [45432]

[+] Listening for events...

Traceback (most recent call last):
  File "/usr/share/responder/./Responder.py", line 359, in <module>
    main()
  File "/usr/share/responder/./Responder.py", line 350, in main
    DHCP()
  File "/usr/share/responder/poisoners/DHCP.py", line 300, in DHCP
    SendDiscover()
  File "/usr/share/responder/poisoners/DHCP.py", line 287, in SendDiscover
    Packet.calculate()
  File "/usr/share/responder/poisoners/DHCP.py", line 155, in calculate
    self.fields["ClientMac"] = GetMacAddress(Interface)
  File "/usr/share/responder/poisoners/DHCP.py", line 93, in GetMacAddress
    mac = netifaces.ifaddresses(Interface)[netifaces.AF_LINK][0]['addr']
KeyError: 17

```

**Comment by lgandx** [comment]
Hello, 

The tun0 interface doesn't have a MAC address, therefore it cause the script to crash.
This issue has been fixed in the last commit. 

Thanks for submitting this issue!
