### ISSUE TITLE
AttributeError: module 'settings' has no attribute 'Config'

### ISSUE THREAD

**Issue by hakanerensan** [lgandx/Responder#180]
When I run dhcp.py, I get an error as follows. I also tried in python virtualenv. I tried it on two different devices.

Edit: I also tried it in wsl2. still same issue continues

````
└─# python3 DHCP.py -I eth0 -r 0.0.0.0 -p 0.0.0.0 -s 0.0.0.0 -n 0.0.0.0 -d "lan" -w "http://DHCP/wpad.dat" -R

Traceback (most recent call last):
  File "/home/kali/impacket/Responder/poisoners/dhcp_test/bin/Responder/poisoners/DHCP.py", line 82, in <module>
    Interface           = settings.Config.Interface
AttributeError: module 'settings' has no attribute 'Config'
                                                                                                                                                                                             
┌──(dhcp_test)─(root💀kali)-[/home/…/dhcp_test/bin/Responder/poisoners]
└─# python3 DHCP.py                                                                                                                                                                      1 ⨯
Traceback (most recent call last):
  File "/home/kali/impacket/Responder/poisoners/dhcp_test/bin/Responder/poisoners/DHCP.py", line 82, in <module>
    Interface           = settings.Config.Interface
AttributeError: module 'settings' has no attribute 'Config' ````

**Comment by lgandx** [comment]
Hello, 
This script is not anymore part of Responder. 
Please get the latest version, and use the -d command switch to use the DHCP module.
