### ISSUE TITLE
Error Starting SSL server on port 5986,443

### ISSUE THREAD

**Issue by denevin** [lgandx/Responder#213]
I'm getting error messages when starting responder version 3.1.3.0 installed from kali repo as root on ports 443 and 5986. These ports don't seem to be used by anything according to netstat and lsof
I can also start netcat listener on these ports without a problem.

```# responder -I eth0

           NBT-NS, LLMNR & MDNS Responder 3.1.3.0

[+] Poisoners:
    LLMNR                      [ON]
    NBT-NS                     [ON]
    MDNS                       [ON]
    DNS                        [ON]
    DHCP                       [OFF]

[+] Servers:
    HTTP server                [ON]
    HTTPS server               [ON]
    WPAD proxy                 [OFF]
    Auth proxy                 [OFF]
    SMB server                 [ON]
    Kerberos server            [ON]
    SQL server                 [ON]
    FTP server                 [ON]
    IMAP server                [ON]
    POP3 server                [ON]
    SMTP server                [ON]
    DNS server                 [ON]
    LDAP server                [ON]
    RDP server                 [ON]
    DCE-RPC server             [ON]
    WinRM server               [ON]

[+] HTTP Options:
    Always serving EXE         [OFF]
    Serving EXE                [OFF]
    Serving HTML               [OFF]
    Upstream Proxy             [OFF]

[+] Poisoning Options:
    Analyze Mode               [OFF]
    Force WPAD auth            [OFF]
    Force Basic Auth           [OFF]
    Force LM downgrade         [OFF]
    Force ESS downgrade        [OFF]

[+] Generic Options:
    Responder NIC              [eth0]
    Responder IP               [REDACTED]
    Responder IPv6             [REDACTED]
    Challenge set              [random]
    Don't Respond To Names     ['ISATAP']

[+] Current Session Variables:
    Responder Machine Name     [REDACTED]
    Responder Domain Name      [REDACTED]
    Responder DCE-RPC Port     [48409]`

[+] Listening for events...

[!] Error starting SSL server on port 5986, check permissions or other servers running.
[!] Error starting SSL server on port 443, check permissions or other servers running.

# netstat -antp
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      33713/sshd: /usr/sb
tcp        0      0 0.0.0.0:8834            0.0.0.0:*               LISTEN      35264/nessusd
tcp        0      1 REDACTED:60324     REDACTED:8888        SYN_SENT    35264/nessusd
tcp        0    248 REDACTED:22        REDACTED:50355       ESTABLISHED 35747/sshd: kali [p
tcp        0      1 REDACTED:37114     REDACTED:8888        SYN_SENT    35264/nessusd
tcp        0      1 REDACTED:49434     REDACTED:8888        SYN_SENT    35264/nessusd
tcp        0      0 REDACTED:42648     REDACTED:80        TIME_WAIT   -
tcp        0      1 REDACTED:47168     REDACTED:8888        SYN_SENT    35264/nessusd
tcp        0      1 REDACTED:36910     REDACTED:111         SYN_SENT    35264/nessusd
tcp6       0      0 :::22                   :::*                    LISTEN      33713/sshd: /usr/sb
tcp6       0      0 :::8834                 :::*                    LISTEN      35264/nessusd

root@kali:/home/kali# nc -nlvp 443
listening on [any] 443 ...

# nc -nlvp 5986
listening on [any] 5986 ...

root@kali:/home/kali# netstat -tulpn | grep :443
root@kali:/home/kali# netstat -tulpn | grep :5986
root@kali:/home/kali# lsof -i :443
root@kali:/home/kali# lsof -i :5986
```

**Comment by denevin** [comment]
For those are are having a similar issue, uninstalling responder using ```apt remove responder --purge```, removing ```/usr/share/responder``` directory and reinstalling it ```apt install responder``` fixed the issue.

The issues with getting the error messages "Error starting SSL server on port x" started happening after the following course of actions.
- impacket-scripts was installed using apt. This upgraded some python libraries at the same time.
- Starting responder resulted in the following error messages on start

```Traceback (most recent call last):
  File "/usr/share/responder/odict.py", line 3, in <module>
    from UserDict import DictMixin
ModuleNotFoundError: No module named 'UserDict'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/responder/./Responder.py", line 350, in <module>
    main()
  File "/usr/share/responder/./Responder.py", line 250, in main
    from poisoners.LLMNR import LLMNR
  File "/usr/share/responder/poisoners/LLMNR.py", line 18, in <module>
    import fingerprint
  File "/usr/share/responder/fingerprint.py", line 22, in <module>
    from packets import SMBHeader, SMBNego, SMBNegoFingerData, SMBSessionFingerData
  File "/usr/share/responder/packets.py", line 25, in <module>
    from odict import OrderedDict
  File "/usr/share/responder/odict.py", line 6, in <module>
    from collections import MutableMapping as DictMixin
ImportError: cannot import name 'MutableMapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
```
- After running command ```apt install --reinstall responder```, the error messages above went away and responder started, but then the "Error starting SSL server on port x" error messages started.
- Running ```apt remove responder --purge``` followed by apt install responder fixed everyting.
