### ISSUE TITLE
You don't have an IPv6 address assigned.

### ISSUE THREAD

**Issue by drxadz** [lgandx/Responder#244]
I am facing this error message  in macbook m1, 

```
sudo python3 Responder.py -i utun7                               255 ↵
                                         __
  .----.-----.-----.-----.-----.-----.--|  |.-----.----.
  |   _|  -__|__ --|  _  |  _  |     |  _  ||  -__|   _|
  |__| |_____|_____|   __|_____|__|__|_____||_____|__|
                   |__|

           NBT-NS, LLMNR & MDNS Responder 3.1.3.0

  To support this project:
  Patreon -> https://www.patreon.com/PythonResponder
  Paypal  -> https://paypal.me/PythonResponder

  Author: Laurent Gaffie (laurent.gaffie@gmail.com)
  To kill this script hit CTRL-C

[+] You don't have an IPv6 address assigned.
Traceback (most recent call last):
  File "/Users/drx/Tools/Responder/Responder.py", line 59, in <module>
    settings.Config.populate(options)
  File "/Users/drx/Tools/Responder/settings.py", line 179, in populate
    self.IP_aton   = socket.inet_aton(self.Bind_To)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: illegal IP address string passed to inet_aton
````
#### network 
![image](https://github.com/lgandx/Responder/assets/84976092/05d3ce0c-41ef-4bca-8f96-dddee9d23fb3)

**Comment by drxadz** [comment]
i have tried to install with pip but still facing many more issues

**Comment by lgandx** [comment]
Hi,

OSX is not supported.

Responder should only be run on Linux.

Thanks,
