### ISSUE TITLE
Error parsing IPv6 in MSSQL server

### ISSUE THREAD

**Issue by firefart** [lgandx/Responder#251]
```text
Exception occurred during processing of request from ('::ffff:10.10.10.10', 63028, 0, 0)
Traceback (most recent call last):
  File "/usr/lib/python3.11/socketserver.py", line 691, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.11/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
  File "/home/firefart/Responder/servers/MSSQL.py", line 172, in handle
    self.send_response(soc, data[1:].rstrip("\x00"))
                            ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: a bytes-like object is required, not 'str'
````

Similar to https://github.com/lgandx/Responder/issues/223

**Comment by exploide** [comment]
Fixed this in #265.
