### ISSUE TITLE
I have this problem, I already  reinstall Responder, but the problem continues | respoder Error SSL

### ISSUE THREAD

**Issue by Shimon03** [lgandx/Responder#268]
┌──(kali㉿readteam)-[~]
└─$ responder
Traceback (most recent call last):
  File "./Responder.py", line 18, in <module>
    import ssl
  File "/usr/local/lib/python3.5/ssl.py", line 99, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: No module named '_ssl'

**Comment by lgandx** [comment]
Seems to be resolved, closing now.
