### ISSUE TITLE
[Kali BUG]

### ISSUE THREAD

**Issue by badboycxcc** [lgandx/Responder#285]
```
[*] [MDNS] Poisoned answer sent to fe80::3c92:6328:40c2:7e2c for name DESKTOP-TUK7B6D(859)._dosvc
[*] [MDNS] Poisoned answer sent to 192.168.7.174   for name DESKTOP-TUK7B6D(861)._dosvc
  File "/home/cx/tools/Responder-master/utils.py", line 406, in SavePoisonersToDb
    cursor.execute("INSERT INTO Poisoned VALUES(datetime('now'), ?, ?, ?, ?)", (result['Poisoner'], result['SentToIp'], result['ForName'], result['AnalyzeMode']))
sqlite3.OperationalError: database is locked
[*] [MDNS] Poisoned answer sent to fe80::3c92:6328:40c2:7e2c for name DESKTOP-TUK7B6D(860)._dosvc
----------------------------------------
[*] [MDNS] Poisoned answer sent to fe80::3c92:6328:40c2:7e2c for name DESKTOP-TUK7B6D(861)._dosvc
[*] [MDNS] Poisoned answer sent to 192.168.7.174   for name DESKTOP-TUK7B6D(862)._dosvc
[*] [MDNS] Poisoned answer sent to 192.168.7.174   for name DESKTOP-TUK7B6D(860)._dosvc
----------------------------------------
sqlite3.OperationalError: database is locked
----------------------------------------
----------------------------------------
Exception occurred during processing of request from ('fe80::3c92:6328:40c2:7e2c', 5353, 0, 2)
Traceback (most recent call last):
  File "/usr/lib/python3.11/socketserver.py", line 691, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.11/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
  File "/home/cx/tools/Responder-master/poisoners/MDNS.py", line 85, in handle
    SavePoisonersToDb({
[*] [MDNS] Poisoned answer sent to fe80::3c92:6328:40c2:7e2c for name DESKTOP-TUK7B6D(862)._dosvc
  File "/home/cx/tools/Responder-master/utils.py", line 406, in SavePoisonersToDb
    cursor.execute("INSERT INTO Poisoned VALUES(datetime('now'), ?, ?, ?, ?)", (result['Poisoner'], result['SentToIp'], result['ForName'], result['AnalyzeMode']))
Traceback (most recent call last):
  File "/usr/lib/python3.11/socketserver.py", line 691, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.11/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
----------------------------------------
----------------------------------------
Exception occurred during processing of request from ('fe80::3c92:6328:40c2:7e2c', 5353, 0, 2)
Traceback (most recent call last):
  File "/usr/lib/python3.11/socketserver.py", line 691, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.11/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
  File "/home/cx/tools/Responder-master/poisoners/MDNS.py", line 85, in handle
    SavePoisonersToDb({
  File "/home/cx/tools/Responder-master/utils.py", line 406, in SavePoisonersToDb
    cursor.execute("INSERT INTO Poisoned VALUES(datetime('now'), ?, ?, ?, ?)", (result['Poisoner'], result['SentToIp'], result['ForName'], result['AnalyzeMode']))
Traceback (most recent call last):
  File "/usr/lib/python3.11/socketserver.py", line 691, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.11/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
Exception ignored in sys.unraisablehook: <built-in function unraisablehook>
KeyboardInterrupt
  File "/home/cx/tools/Responder-master/utils.py", line 406, in SavePoisonersToDb
    cursor.execute("INSERT INTO Poisoned VALUES(datetime('now'), ?, ?, ?, ?)", (result['Poisoner'], result['SentToIp'], result['ForName'], result['AnalyzeMode']))
sqlite3.OperationalError: database is locked
Traceback (most recent call last):
  File "/usr/lib/python3.11/socketserver.py", line 691, in process_request_thread
    self.finish_request(request, client_address)
[*] [MDNS] Poisoned answer sent to 192.168.7.174   for name DESKTOP-TUK7B6D(863)._dosvc
  File "/usr/lib/python3.11/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.11/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
[*] [MDNS] Poisoned answer sent to fe80::3c92:6328:40c2:7e2c for name DESKTOP-TUK7B6D(863)._dosvc
  File "/home/cx/tools/Responder-master/poisoners/MDNS.py", line 85, in handle
    SavePoisonersToDb({
  File "/home/cx/tools/Responder-master/utils.py", line 406, in SavePoisonersToDb
    cursor.execute("INSERT INTO Poisoned VALUES(datetime('now'), ?, ?, ?, ?)", (result['Poisoner'], result['SentToIp'], result['ForName'], result['AnalyzeMode']))
[*] [MDNS] Poisoned answer sent to 192.168.7.174   for name DESKTOP-TUK7B6D(864)._dosvc
sqlite3.OperationalError: database is locked
----------------------------------------
----------------------------------------
sqlite3.OperationalError: database is locked
----------------------------------------
----------------------------------------
Exception occurred during processing of request from ('fe80::3c92:6328:40c2:7e2c', 5353, 0, 2)
Exception occurred during processing of request from ('::ffff:192.168.7.174', 5353, 0, 0)
[*] [MDNS] Poisoned answer sent to fe80::3c92:6328:40c2:7e2c for name DESKTOP-TUK7B6D(864)._dosvc
^C  File "/usr/lib/python3.11/socketserver.py", line 691, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.11/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
  File "/home/cx/tools/Responder-master/poisoners/MDNS.py", line 85, in handle
    SavePoisonersToDb({
  File "/home/cx/tools/Responder-master/utils.py", line 406, in SavePoisonersToDb
    cursor.execute("INSERT INTO Poisoned VALUES(datetime('now'), ?, ?, ?, ?)", (result['Poisoner'], result['SentToIp'], result['ForName'], result['AnalyzeMode']))
sqlite3.OperationalError: database is locked
----------------------------------------
  File "/usr/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
[*] [MDNS] Poisoned answer sent to 192.168.7.174   for name DESKTOP-TUK7B6D(865)._dosvc
  File "/home/cx/tools/Responder-master/poisoners/MDNS.py", line 85, in handle
    SavePoisonersToDb({
----------------------------------------
----------------------------------------
Exception occurred during processing of request from ('::ffff:192.168.7.174', 5353, 0, 0)
Traceback (most recent call last):
[*] [MDNS] Poisoned answer sent to fe80::3c92:6328:40c2:7e2c for name DESKTOP-TUK7B6D(865)._dosvc
  File "/usr/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
  File "/home/cx/tools/Responder-master/poisoners/MDNS.py", line 85, in handle
    SavePoisonersToDb({
  File "/home/cx/tools/Responder-master/utils.py", line 406, in SavePoisonersToDb
    cursor.execute("INSERT INTO Poisoned VALUES(datetime('now'), ?, ?, ?, ?)", (result['Poisoner'], result['SentToIp'], result['ForName'], result['AnalyzeMode']))
sqlite3.OperationalError: database is locked
----------------------------------------
  File "/home/cx/tools/Responder-master/utils.py", line 406, in SavePoisonersToDb
    cursor.execute("INSERT INTO Poisoned VALUES(datetime('now'), ?, ?, ?, ?)", (result['Poisoner'], result['SentToIp'], result['ForName'], result['AnalyzeMode']))
[*] [MDNS] Poisoned answer sent to 192.168.7.174   for name DESKTOP-TUK7B6D(866)._dosvc
  File "/usr/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
Traceback (most recent call last):
  File "/usr/lib/python3.11/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
  File "/home/cx/tools/Responder-master/poisoners/MDNS.py", line 85, in handle
    SavePoisonersToDb({
  File "/home/cx/tools/Responder-master/utils.py", line 406, in SavePoisonersToDb
    cursor.execute("INSERT INTO Poisoned VALUES(datetime('now'), ?, ?, ?, ?)", (result['Poisoner'], result['SentToIp'], result['ForName'], result['AnalyzeMode']))
sqlite3.OperationalError: database is locked
----------------------------------------
Exception ignored in atexit callback: <function shutdown at 0x7fd04f273ce0>
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python3.11/socketserver.py", line 691, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.11/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
[*] [MDNS] Poisoned answer sent to fe80::3c92:6328:40c2:7e2c for name DESKTOP-TUK7B6D(866)._dosvc
sqlite3.OperationalError: database is locked
----------------------------------------
Traceback (most recent call last):
----------------------------------------
Exception occurred during processing of request from ('::ffff:192.168.7.174', 5353, 0, 0)
  File "/usr/lib/python3.11/socketserver.py", line 691, in process_request_thread
    self.finish_request(request, client_address)
  File "/home/cx/tools/Responder-master/poisoners/MDNS.py", line 85, in handle
    SavePoisonersToDb({
  File "/home/cx/tools/Responder-master/utils.py", line 406, in SavePoisonersToDb
    cursor.execute("INSERT INTO Poisoned VALUES(datetime('now'), ?, ?, ?, ?)", (result['Poisoner'], result['SentToIp'], result['ForName'], result['AnalyzeMode']))
sqlite3.OperationalError: database is locked
----------------------------------------
----------------------------------------
Exception occurred during processing of request from ('fe80::3c92:6328:40c2:7e2c', 5353, 0, 2)
----------------------------------------
Exception occurred during processing of request from ('fe80::3c92:6328:40c2:7e2c', 5353, 0, 2)
  File "/usr/lib/python3.11/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
----------------------------------------
Exception occurred during processing of request from ('::ffff:192.168.7.174', 5353, 0, 0)
[*] [MDNS] Poisoned answer sent to 192.168.7.174   for name DESKTOP-TUK7B6D(867)._dosvc
Traceback (most recent call last):
[*] [MDNS] Poisoned answer sent to fe80::3c92:6328:40c2:7e2c for name DESKTOP-TUK7B6D(867)._dosvc
  File "/usr/lib/python3.11/socketserver.py", line 691, in process_request_thread
    self.finish_request(request, client_address)
  File "/home/cx/tools/Responder-master/poisoners/MDNS.py", line 85, in handle
    SavePoisonersToDb({
  File "/home/cx/tools/Responder-master/utils.py", line 406, in SavePoisonersToDb
    cursor.execute("INSERT INTO Poisoned VALUES(datetime('now'), ?, ?, ?, ?)", (result['Poisoner'], result['SentToIp'], result['ForName'], result['AnalyzeMode']))
[*] [MDNS] Poisoned answer sent to 192.168.7.174   for name DESKTOP-TUK7B6D(868)._dosvc
  File "/usr/lib/python3.11/socketserver.py", line 691, in process_request_thread
    self.finish_request(request, client_address)
----------------------------------------
Exception occurred during processing of request from ('fe80::3c92:6328:40c2:7e2c', 5353, 0, 2)
[*] [MDNS] Poisoned answer sent to fe80::3c92:6328:40c2:7e2c for name DESKTOP-TUK7B6D(868)._dosvc
[*] [MDNS] Poisoned answer sent to 192.168.7.174   for name DESKTOP-TUK7B6D(869)._dosvc
[*] [MDNS] Poisoned answer sent to fe80::3c92:6328:40c2:7e2c for name DESKTOP-TUK7B6D(869)._dosvc
  File "/usr/lib/python3.11/logging/__init__.py", line 2192, in shutdown
  File "/usr/lib/python3.11/socketserver.py", line 691, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.11/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
  File "/home/cx/tools/Responder-master/poisoners/MDNS.py", line 85, in handle
    SavePoisonersToDb({
  File "/home/cx/tools/Responder-master/utils.py", line 406, in SavePoisonersToDb
    cursor.execute("INSERT INTO Poisoned VALUES(datetime('now'), ?, ?, ?, ?)", (result['Poisoner'], result['SentToIp'], result['ForName'], result['AnalyzeMode']))
Traceback (most recent call last):
----------------------------------------
Exception occurred during processing of request from ('fe80::3c92:6328:40c2:7e2c', 5353, 0, 2)
Exception occurred during processing of request from ('::ffff:192.168.7.174', 5353, 0, 0)
----------------------------------------
Exception occurred during processing of request from ('::ffff:192.168.7.174', 5353, 0, 0)
  File "/home/cx/tools/Responder-master/poisoners/MDNS.py", line 85, in handle
    SavePoisonersToDb({
Traceback (most recent call last):
  File "/usr/lib/python3.11/socketserver.py", line 691, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
  File "/home/cx/tools/Responder-master/poisoners/MDNS.py", line 85, in handle
    SavePoisonersToDb({
  File "/home/cx/tools/Responder-master/utils.py", line 406, in SavePoisonersToDb
    cursor.execute("INSERT INTO Poisoned VALUES(datetime('now'), ?, ?, ?, ?)", (result['Poisoner'], result['SentToIp'], result['ForName'], result['AnalyzeMode']))
sqlite3.OperationalError: database is locked
----------------------------------------
----------------------------------------
Exception occurred during processing of request from ('::ffff:192.168.7.174', 5353, 0, 0)
----------------------------------------
Exception occurred during processing of request from ('fe80::3c92:6328:40c2:7e2c', 5353, 0, 2)
  File "/usr/lib/python3.11/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
  File "/home/cx/tools/Responder-master/poisoners/MDNS.py", line 85, in handle
    SavePoisonersToDb({
  File "/home/cx/tools/Responder-master/utils.py", line 406, in SavePoisonersToDb
    cursor.execute("INSERT INTO Poisoned VALUES(datetime('now'), ?, ?, ?, ?)", (result['Poisoner'], result['SentToIp'], result['ForName'], result['AnalyzeMode']))
sqlite3.OperationalError: database is locked
----------------------------------------
[*] [MDNS] Poisoned answer sent to 192.168.7.174   for name DESKTOP-TUK7B6D(870)._dosvc
----------------------------------------
  File "/usr/lib/python3.11/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
^C[*] [MDNS] Poisoned answer sent to fe80::3c92:6328:40c2:7e2c for name DESKTOP-TUK7B6D(870)._dosvc
[*] [MDNS] Poisoned answer sent to 192.168.7.174   for name DESKTOP-TUK7B6D(871)._dosvc
sqlite3.OperationalError: database is locked
----------------------------------------
  File "/usr/lib/python3.11/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
  File "/home/cx/tools/Responder-master/poisoners/MDNS.py", line 85, in handle
    SavePoisonersToDb({
Traceback (most recent call last):
  File "/usr/lib/python3.11/socketserver.py", line 691, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.11/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
  File "/home/cx/tools/Responder-master/poisoners/MDNS.py", line 85, in handle
    SavePoisonersToDb({
  File "/home/cx/tools/Responder-master/utils.py", line 406, in SavePoisonersToDb
    cursor.execute("INSERT INTO Poisoned VALUES(datetime('now'), ?, ?, ?, ?)", (result['Poisoner'], result['SentToIp'], result['ForName'], result['AnalyzeMode']))
sqlite3.OperationalError: database is locked
----------------------------------------
  File "/home/cx/tools/Responder-master/utils.py", line 406, in SavePoisonersToDb
    cursor.execute("INSERT INTO Poisoned VALUES(datetime('now'), ?, ?, ?, ?)", (result['Poisoner'], result['SentToIp'], result['ForName'], result['AnalyzeMode']))
sqlite3.OperationalError: database is locked
----------------------------------------
Traceback (most recent call last):
sqlite3.OperationalError: database is locked
[*] [MDNS] Poisoned answer sent to fe80::3c92:6328:40c2:7e2c for name DESKTOP-TUK7B6D(871)._dosvc
[*] [MDNS] Poisoned answer sent to 192.168.7.174   for name DESKTOP-TUK7B6D(872)._dosvc
----------------------------------------
Exception occurred during processing of request from ('::ffff:192.168.7.174', 5353, 0, 0)
Traceback (most recent call last):
  File "/usr/lib/python3.11/socketserver.py", line 691, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.11/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
  File "/home/cx/tools/Responder-master/poisoners/MDNS.py", line 85, in handle
    SavePoisonersToDb({
----------------------------------------
Exception occurred during processing of request from ('fe80::3c92:6328:40c2:7e2c', 5353, 0, 2)
[*] [MDNS] Poisoned answer sent to fe80::3c92:6328:40c2:7e2c for name DESKTOP-TUK7B6D(872)._dosvc
sqlite3.OperationalError: database is locked
----------------------------------------
----------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.11/socketserver.py", line 691, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.11/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
  File "/home/cx/tools/Responder-master/poisoners/MDNS.py", line 85, in handle
    SavePoisonersToDb({
Traceback (most recent call last):
----------------------------------------
Exception occurred during processing of request from ('::ffff:192.168.7.174', 5353, 0, 0)
Traceback (most recent call last):
[*] [MDNS] Poisoned answer sent to 192.168.7.174   for name DESKTOP-TUK7B6D(873)._dosvc
  File "/usr/lib/python3.11/socketserver.py", line 691, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.11/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
[*] [MDNS] Poisoned answer sent to fe80::3c92:6328:40c2:7e2c for name DESKTOP-TUK7B6D(873)._dosvc
  File "/usr/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
[*] [MDNS] Poisoned answer sent to 192.168.7.174   for name DESKTOP-TUK7B6D(874)._dosvc
Traceback (most recent call last):
[*] [MDNS] Poisoned answer sent to fe80::3c92:6328:40c2:7e2c for name DESKTOP-TUK7B6D(874)._dosvc
Traceback (most recent call last):
  File "/usr/lib/python3.11/socketserver.py", line 691, in process_request_thread
    self.finish_request(request, client_address)
  File "/home/cx/tools/Responder-master/utils.py", line 406, in SavePoisonersToDb
    cursor.execute("INSERT INTO Poisoned VALUES(datetime('now'), ?, ?, ?, ?)", (result['Poisoner'], result['SentToIp'], result['ForName'], result['AnalyzeMode']))
sqlite3.OperationalError: database is locked
----------------------------------------
----------------------------------------
Exception occurred during processing of request from ('fe80::3c92:6328:40c2:7e2c', 5353, 0, 2)
  File "/usr/lib/python3.11/socketserver.py", line 691, in process_request_thread
    self.finish_request(request, client_address)
[*] [MDNS] Poisoned answer sent to fe80::3c92:6328:40c2:7e2c for name DESKTOP-TUK7B6D(875)._dosvc
  File "/usr/lib/python3.11/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
  File "/home/cx/tools/Responder-master/poisoners/MDNS.py", line 85, in handle
    SavePoisonersToDb({
----------------------------------------
Exception occurred during processing of request from ('::ffff:192.168.7.174', 5353, 0, 0)
  File "/usr/lib/python3.11/socketserver.py", line 691, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.11/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
[*] [MDNS] Poisoned answer sent to 192.168.7.174   for name DESKTOP-TUK7B6D(875)._dosvc
----------------------------------------
Exception occurred during processing of request from ('::ffff:192.168.7.174', 5353, 0, 0)
----------------------------------------
  File "/usr/lib/python3.11/logging/__init__.py", line 1094, in flush
[*] [MDNS] Poisoned answer sent to 192.168.7.174   for name DESKTOP-TUK7B6D(876)._dosvc
  File "/home/cx/tools/Responder-master/poisoners/MDNS.py", line 85, in handle
    SavePoisonersToDb({
----------------------------------------
Exception occurred during processing of request from ('fe80::3c92:6328:40c2:7e2c', 5353, 0, 2)
Traceback (most recent call last):
  File "/usr/lib/python3.11/socketserver.py", line 691, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.11/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
[*] [MDNS] Poisoned answer sent to fe80::3c92:6328:40c2:7e2c for name DESKTOP-TUK7B6D(876)._dosvc
Exception occurred during processing of request from ('::ffff:192.168.7.174', 5353, 0, 0)
  File "/home/cx/tools/Responder-master/utils.py", line 406, in SavePoisonersToDb
    cursor.execute("INSERT INTO Poisoned VALUES(datetime('now'), ?, ?, ?, ?)", (result['Poisoner'], result['SentToIp'], result['ForName'], result['AnalyzeMode']))
Traceback (most recent call last):
  File "/usr/lib/python3.11/socketserver.py", line 691, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.11/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
Exception occurred during processing of request from ('::ffff:192.168.7.174', 5353, 0, 0)
Traceback (most recent call last):
  File "/usr/lib/python3.11/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
  File "/home/cx/tools/Responder-master/poisoners/MDNS.py", line 85, in handle
    SavePoisonersToDb({
  File "/home/cx/tools/Responder-master/utils.py", line 406, in SavePoisonersToDb
    cursor.execute("INSERT INTO Poisoned VALUES(datetime('now'), ?, ?, ?, ?)", (result['Poisoner'], result['SentToIp'], result['ForName'], result['AnalyzeMode']))
sqlite3.OperationalError: database is locked
----------------------------------------
Traceback (most recent call last):
[*] [MDNS] Poisoned answer sent to 192.168.7.174   for name DESKTOP-TUK7B6D(877)._dosvc
  File "/home/cx/tools/Responder-master/utils.py", line 406, in SavePoisonersToDb
    cursor.execute("INSERT INTO Poisoned VALUES(datetime('now'), ?, ?, ?, ?)", (result['Poisoner'], result['SentToIp'], result['ForName'], result['AnalyzeMode']))
sqlite3.OperationalError: database is locked
----------------------------------------
  File "/home/cx/tools/Responder-master/utils.py", line 406, in SavePoisonersToDb
    cursor.execute("INSERT INTO Poisoned VALUES(datetime('now'), ?, ?, ?, ?)", (result['Poisoner'], result['SentToIp'], result['ForName'], result['AnalyzeMode']))
sqlite3.OperationalError: database is locked
----------------------------------------
  File "/usr/lib/python3.11/socketserver.py", line 691, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.11/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
  File "/home/cx/tools/Responder-master/poisoners/MDNS.py", line 85, in handle
    SavePoisonersToDb({
  File "/home/cx/tools/Responder-master/utils.py", line 406, in SavePoisonersToDb
    cursor.execute("INSERT INTO Poisoned VALUES(datetime('now'), ?, ?, ?, ?)", (result['Poisoner'], result['SentToIp'], result['ForName'], result['AnalyzeMode']))
sqlite3.OperationalError: database is locked
----------------------------------------
  File "/home/cx/tools/Responder-master/poisoners/MDNS.py", line 85, in handle
    SavePoisonersToDb({
Traceback (most recent call last):
  File "/home/cx/tools/Responder-master/utils.py", line 406, in SavePoisonersToDb
    cursor.execute("INSERT INTO Poisoned VALUES(datetime('now'), ?, ?, ?, ?)", (result['Poisoner'], result['SentToIp'], result['ForName'], result['AnalyzeMode']))
sqlite3.OperationalError: database is locked
----------------------------------------
  File "/usr/lib/python3.11/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
  File "/home/cx/tools/Responder-master/poisoners/MDNS.py", line 85, in handle
    SavePoisonersToDb({
  File "/home/cx/tools/Responder-master/utils.py", line 406, in SavePoisonersToDb
    cursor.execute("INSERT INTO Poisoned VALUES(datetime('now'), ?, ?, ?, ?)", (result['Poisoner'], result['SentToIp'], result['ForName'], result['AnalyzeMode']))
sqlite3.OperationalError: database is locked
----------------------------------------
  File "/usr/lib/python3.11/socketserver.py", line 691, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.11/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
  File "/home/cx/tools/Responder-master/poisoners/MDNS.py", line 85, in handle
    SavePoisonersToDb({
  File "/home/cx/tools/Responder-master/utils.py", line 406, in SavePoisonersToDb
    cursor.execute("INSERT INTO Poisoned VALUES(datetime('now'), ?, ?, ?, ?)", (result['Poisoner'], result['SentToIp'], result['ForName'], result['AnalyzeMode']))
sqlite3.OperationalError: database is locked
----------------------------------------
----------------------------------------
Exception occurred during processing of request from ('fe80::3c92:6328:40c2:7e2c', 5353, 0, 2)
Traceback (most recent call last):
  File "/usr/lib/python3.11/socketserver.py", line 691, in process_request_thread
    self.finish_request(request, client_address)
  File "/home/cx/tools/Responder-master/poisoners/MDNS.py", line 85, in handle
    SavePoisonersToDb({
  File "/home/cx/tools/Responder-master/utils.py", line 406, in SavePoisonersToDb
    cursor.execute("INSERT INTO Poisoned VALUES(datetime('now'), ?, ?, ?, ?)", (result['Poisoner'], result['SentToIp'], result['ForName'], result['AnalyzeMode']))
sqlite3.OperationalError: database is locked
^CTraceback (most recent call last):
  File "/usr/lib/python3.11/socketserver.py", line 691, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.11/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
  File "/home/cx/tools/Responder-master/poisoners/MDNS.py", line 85, in handle
    SavePoisonersToDb({
  File "/home/cx/tools/Responder-master/utils.py", line 406, in SavePoisonersToDb
    cursor.execute("INSERT INTO Poisoned VALUES(datetime('now'), ?, ?, ?, ?)", (result['Poisoner'], result['SentToIp'], result['ForName'], result['AnalyzeMode']))
sqlite3.OperationalError: database is locked
  File "/usr/lib/python3.11/socketserver.py", line 691, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.11/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.11/socketserver.py", line 691, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.11/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
Traceback (most recent call last):
  File "/usr/lib/python3.11/socketserver.py", line 691, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.11/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
  File "/home/cx/tools/Responder-master/poisoners/MDNS.py", line 85, in handle
    SavePoisonersToDb({
  File "/home/cx/tools/Responder-master/utils.py", line 406, in SavePoisonersToDb
    cursor.execute("INSERT INTO Poisoned VALUES(datetime('now'), ?, ?, ?, ?)", (result['Poisoner'], result['SentToIp'], result['ForName'], result['AnalyzeMode']))
sqlite3.OperationalError: database is locked
----------------------------------------
  File "/usr/lib/python3.11/socketserver.py", line 691, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.11/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
  File "/home/cx/tools/Responder-master/poisoners/MDNS.py", line 85, in handle
    SavePoisonersToDb({
  File "/home/cx/tools/Responder-master/utils.py", line 406, in SavePoisonersToDb
    cursor.execute("INSERT INTO Poisoned VALUES(datetime('now'), ?, ?, ?, ?)", (result['Poisoner'], result['SentToIp'], result['ForName'], result['AnalyzeMode']))
sqlite3.OperationalError: database is locked
----------------------------------------
    self.stream.flush()
KeyboardInterrupt: 
^C^CFatal Python error: _enter_buffered_busy: could not acquire lock for <ascii(self) failed> at interpreter shutdown, possibly due to daemon threads
Python runtime state: finalizing (tstate=0x0000000000a78d38)
zsh: IOT instruction  sudo python3 Responder.py -I eth0 -wd

```

**Comment by L1-0** [comment]
Experiencing the same, with slightly different stack traces.

`File "/usr/lib/python3.11/socketserver.py", line 691, in process_request_thread`
`File "/usr/lib/python3.11/socketserver.py", line 755, in __init__`
`File "/usr/share/responder/poisoners/MDNS.py", line 78, in handle`

**Comment by i-am4man** [comment]
Having same issue here. I'm also getting what the above is getting and database locked. 

Exception occurred during processing of request from ('::ffff:10.10.10.10', 5353, 0, 0)
Traceback (most recent call last):
----------------------------------------
Exception occurred during processing of request from ('IPv6removed', 5353, 0, 2)
Traceback (most recent call last):
  File "/usr/lib/python3.11/socketserver.py", line 691, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.11/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
  File "/usr/share/responder/poisoners/MDNS.py", line 78, in handle
    SavePoisonersToDb({
Traceback (most recent call last):
  File "/usr/lib/python3.11/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
  File "/usr/share/responder/poisoners/MDNS.py", line 78, in handle
    SavePoisonersToDb({
  File "/usr/share/responder/utils.py", line 391, in SavePoisonersToDb
    cursor = sqlite3.connect(settings.Config.DatabaseFile)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by lgandx** [comment]
This issue has been resolved in https://github.com/lgandx/Responder/commit/e918fe01c617e482d8b24525db581c403104ab28
