### ISSUE TITLE
sqlite3.OperationalError: unable to open database file repeated exception

### ISSUE THREAD

**Issue by garilla2** [lgandx/Responder#293]
On the latest clean and updated version of kali (tried multiple old updated boxes, and clean installs)

PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
VERSION_ID="2024.3"
VERSION="2024.3"
VERSION_CODENAME=kali-rolling
ID=kali
ID_LIKE=debian
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"
ANSI_COLOR="1;31"

We are getting repeated errors using responder as below:

[*] [MDNS] Poisoned answer sent to 192.168.X.X for name LAPTOP-XXXXXX(6681)._dosvc
----------------------------------------
Exception occurred during processing of request from ('::ffff:192.168.X.X', 5353, 0, 0)
Traceback (most recent call last):
  File "/usr/lib/python3.11/socketserver.py", line 691, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.11/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
  File "/usr/share/responder/poisoners/MDNS.py", line 78, in handle
    SavePoisonersToDb({
  File "/usr/share/responder/utils.py", line 391, in SavePoisonersToDb
    cursor = sqlite3.connect(settings.Config.DatabaseFile)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file

![s1](https://github.com/user-attachments/assets/48818651-558c-450c-a271-315ee599e681)

**Comment by lgandx** [comment]
Hi there,

This was fixed in Responder, not sure why Kali didn't update it yet.

You can always download and run Responder locally.

**Comment by garilla2** [comment]
Thank you for timely response, will do so.

**Comment by fgeek** [comment]
@garilla2 Did you get Responder working from git? Can you close this issue if you did?

**Comment by garilla2** [comment]
Good morning, and apologies for my tardy response. I used your version as recommended, and while there was less verbosity in the error generation, I had the exact same sqllite errors as above.

**Comment by lgandx** [comment]
Can you provide the command line you used to launch Responder?

**Comment by lgandx** [comment]
Closing this issue
