### ISSUE TITLE
Random challenge issues

### ISSUE THREAD

**Issue by moomarks** [lgandx/Responder#31]
Found these issues randomly 

Exception happened during processing of request from ('*.*.*.102', 63777)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/*/Responder/servers/HTTP.py", line 269, in handle
    Challenge = RandomChallenge()
  File "/*/Responder/utils.py", line 32, in RandomChallenge
    Challenge += NumChal[i:i+2].decode("hex")
  File "/usr/lib/python2.7/encodings/hex_codec.py", line 42, in hex_decode
    output = binascii.a2b_hex(input)
TypeError: Odd-length string

**search everywhere , but couldnt find any solution, 
Tried adding "strip()" to  NumChal[i:i+2].decode("hex") 
Errors remain same but another error is thrown also**

Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
[!]  Fingerprint failed
    self.finish_request(request, client_address)
[!]  Fingerprint failed
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
172.168.9.113 - - [24/Jan/2017 07:06:28] "CONNECT microsoft.stream1.fyre.co:443 HTTP/1.1" 404 -
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe

any one please help

**Comment by moomarks** [comment]
**Another error after changing it to Challenge += NumChal[i:i+2].replace(' ', '').decode("hex")


Somehow the random challenge generation has issues**

Exception happened during processing of request from ('', 60596)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/root/Responder/poisoners/LLMNR.py", line 51, in handle
    Name = Parse_LLMNR_Name(data)
  File "/root/Responder/poisoners/LLMNR.py", line 26, in Parse_LLMNR_Name
    NameLen = struct.unpack('>B',data[12])[0]
IndexError: string index out of range

**Comment by benichmt1** [comment]
Same issue, Kali 2.0

**Comment by Gifts** [comment]
Try applying this patch. Problem is - getrandbits can generate less than 64 bits value and the value should be padded with zeros.

```diff
diff --git a/utils.py b/utils.py
index 011c7ef..a1f0ba6 100644
--- a/utils.py
+++ b/utils.py
@@ -31,7 +31,7 @@ except ImportError:
 def RandomChallenge():
     if settings.Config.NumChal == "random":
        from random import getrandbits
-       NumChal = '%0x' % getrandbits(16 * 4)
+       NumChal = '%016x' % getrandbits(16 * 4)
        Challenge = ''
        for i in range(0, len(NumChal),2):
           Challenge += NumChal[i:i+2].decode("hex")
```
