### ISSUE TITLE
Error while running Responder

### ISSUE THREAD

**Issue by c0d3xpl0it** [lgandx/Responder#36]
While running latest version of responder I got below error

root@kali:~/Responder# python Responder.py -I eth1

[+] Listening for events...
[*] [NBT-NS] Poisoned answer sent to 10.7.1.2 for name CDE (service: File Server)
----------------------------------------
Exception happened during processing of request from ('10.7.1.2', 137)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/root/Responder/poisoners/NBTNS.py", line 75, in handle
    'AnalyzeMode': '0',
  File "/root/Responder/utils.py", line 236, in SavePoisonersToDb
    res = cursor.execute("SELECT COUNT(*) AS count FROM Poisoned WHERE Poisoner=? AND SentToIp=? AND ForName=? AND AnalyzeMode=?", (result['Poisoner'], result['SentToIp'], result['ForName'], result['AnalyzeMode']))
OperationalError: no such table: Poisoned
----------------------------------------
[*] [NBT-NS] Poisoned answer sent to 10.7.1.2 for name IT (service: File Server)
----------------------------------------
Exception happened during processing of request from ('10.7.1.2', 137)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/root/Responder/poisoners/NBTNS.py", line 75, in handle
    'AnalyzeMode': '0',
  File "/root/Responder/utils.py", line 236, in SavePoisonersToDb
    res = cursor.execute("SELECT COUNT(*) AS count FROM Poisoned WHERE Poisoner=? AND SentToIp=? AND ForName=? AND AnalyzeMode=?", (result['Poisoner'], result['SentToIp'], result['ForName'], result['AnalyzeMode']))
OperationalError: no such table: Poisoned
----------------------------------------
[+] Exiting...
root@kali:~/Responder#

**Comment by lgandx** [comment]
You probably git pull on a version you already used. To solve this issue, you need to:
rm Responder.db and lauch Responder again

**Comment by c0d3xpl0it** [comment]
Thank you. It resolved the issue.
