### ISSUE TITLE
DumpHash.py Error

### ISSUE THREAD

**Issue by benichmt1** [lgandx/Responder#43]
Whenever I run DumpHash.py, it spits out an error. For whatever reason, I got some weird output in my Responder that looks like Chinese characters. I believe this might be the root cause.

```
Dumping NTLMV2 hashes:
Traceback (most recent call last):
  File "./DumpHash.py", line 43, in <module>
    v2 = GetResponderCompleteNTLMv2Hash(cursor)
  File "./DumpHash.py", line 31, in GetResponderCompleteNTLMv2Hash
    Output += '{0}'.format(row[0])+'\n'
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
```
```
             Ò舕̆▀ༀ叧쀮玘ਤ埘钮hostname
[SMBv2] NTLMv2-SSP Hash     : 䵌卓P¢ºXv
                                                Ò舕̆▀ༀ叧쀮玘ਤ埘钮hostname::䵌卓P¢ºXv
                             Ò舕̆▀ༀ叧쀮玘ਤ埘钮S:49b183a9c2971aff:4C4D535350000300000018001800A200:000018001800BA0000001E001E00580000000E000E00760000001E001E008400[redacted]
```

**Comment by lgandx** [comment]
Was it a pentest on a chinese network? :)
