### ISSUE TITLE
RunFinger on Windows 2000/2003 hosts fails

### ISSUE THREAD

**Issue by eapolsniper** [lgandx/Responder#84]
I realllly wish I didn't have to submit this...because..Windows 2000...

When running RunFinger against Windows 2000 and possibly Server 2003 hosts while using the grep out mode mode (-g), stack traces are displayed instead of output. Running without being in grep mode works fine.

Output for the traces are displayed below:

Process Process-314:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "RunFinger.py", line 249, in ShowSmallResults
    NullSess, Ms17010 = SmbNullSession(Host)
TypeError: 'NoneType' object is not iterable
Process Process-171:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "RunFinger.py", line 249, in ShowSmallResults
    NullSess, Ms17010 = SmbNullSession(Host)
TypeError: 'NoneType' object is not iterable
Process Process-181:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "RunFinger.py", line 249, in ShowSmallResults
    NullSess, Ms17010 = SmbNullSession(Host)
TypeError: 'NoneType' object is not iterable

**Comment by lgandx** [comment]
Could you please provide a pcap file, so I can debug this issue?
Thanks!
